// client/src/ng-ts/app/components/order/checkout.component.ts
import { Component, OnInit } from '@angular/core';
import { Cart } from '../cart/cart';
import { CartService } from '../cart/cart.service';
import { Address } from './address';
import { OrderService } from './order.service';

@Component({
  selector: 'checkout',
  templateUrl: 'checkout.component.html',
})
export class CheckoutComponent implements OnInit {
  cart: Cart | any = { items: [] };
  billingAddress: Address;
  shippingAddress: Address;

  constructor(private cartService: CartService, private orderService: OrderService) {}

  ngOnInit(): void {
    this.cartService.cartSubject.subscribe(cart => this.cart = cart);
    this.billingAddress = {
      fullName: '<fullName>',
      address1: '<address1>',
      address2: '<address2>',
      city: '<city>',
      state: '<state>',
      country: '<country>',
      zipCode: '<zipCode>',
      phone: '<phone>',
      email: '<email>'
    };
    this.shippingAddress = {
      fullName: '<fullName>',
      address1: '<address1>',
      address2: '<address2>',
      city: '<city>',
      state: '<state>',
      country: '<country>',
      zipCode: '<zipCode>',
      phone: '<phone>',
      email: '<email>'
    };
  }

  placeOrder() {
    this.orderService.placeOrder(this.billingAddress, this.shippingAddress);
  }
}
<div>
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a [routerLink]="['/']">Home</a></li>
      <li class="breadcrumb-item"><a [routerLink]="['/cart']">Cart</a></li>
      <li class="breadcrumb-item active">Checkout</li>
    </ol>
    <div class="container-fluid">
      <div class="row">
        <div class="col-6">
          <h5>Order Address</h5>
          <order-address [addr]="billingAddress"></order-address>
          <h5>Shipping Address</h5>
          <order-address [addr]="shippingAddress"></order-address>
        </div>
        <div class="col-6">
          <button class="btn btn-primary float-right mb-3" (click)="placeOrder()">Order</button>
          <table class="table table-sm table-striped table-hover">
            <thead class="thead-light">
              <tr>
                <th scope="col">#</th>
                <th scope="col">Product</th>
                <th scope="col" class="text-right">Price</th>
                <th scope="col" class="text-right">Quantity</th>
                <th scope="col" class="text-right">Total</th>
              </tr>
            </thead>
            <tbody>
              <tr *ngFor="let cartItem of cart.items; let idx = index">
                <th scope="row">{{idx + 1}}</th>
                <td>{{cartItem.item.product.name}} {{cartItem.item.name}}</td>
                <td class="text-right">{{(cartItem.item.price / 100) | currency}}</td>
                <td class="text-right">{{cartItem.quantity}}</td>
                <td class="text-right">{{(cartItem.item.price * cartItem.quantity) / 100 | currency}}</td>
              </tr>
            </tbody>
            <tfoot class="thead-light">
              <tr>
                <th scope="col" colspan="5" class="text-right">{{(cart.total / 100) | currency}}</th>
              </tr>
            </tfoot>
          </table>
          <button class="btn btn-primary float-right" (click)="placeOrder()">Order</button>
        </div>
      </div>
    </div>
  </div>

// src/main/webapp/scripts/app/checkout/checkout.jsx
var Checkout = React.createClass({
    render: function() {
        return <ContainerFluid>
            <Row>
                <Column colSpan="4">
                    <label className="text-primary">Shipping Address</label>
                    <address>
                        <strong>{this.state.order.shippingAddress.fullName}</strong><br />
                        {this.state.order.shippingAddress.address1}<br />
                        {this.state.order.shippingAddress.address2}<br />
                        {this.state.order.shippingAddress.city}, {this.state.order.shippingAddress.state} {this.state.order.shippingAddress.zip}<br />
                        {this.state.order.shippingAddress.country}<br />
                        <abbr title="Phone">P:</abbr> {this.state.order.shippingAddress.phoneNumber}<br /><br />
                        <Button text="Edit Shipping Address" />
                    </address>
                </Column>
                <Column colSpan="4">
                    <label className="text-primary">Billing Address</label>
                    <address>
                        <strong>{this.state.order.billingAddress.fullName}</strong><br />
                        {this.state.order.billingAddress.address1}<br />
                        {this.state.order.billingAddress.address2}<br />
                        {this.state.order.billingAddress.city}, {this.state.order.billingAddress.state} {this.state.order.billingAddress.zip}<br />
                        {this.state.order.billingAddress.country}<br />
                        <abbr title="Phone">P:</abbr> {this.state.order.billingAddress.phoneNumber}<br /><br />
                        <Button text="Edit Billing Address" />
                    </address>
                </Column>
                <Column colSpan="4">
                    <Table cls="cart-table">
                        <thead>
                            <tr>
                                <th className="text-center">&nbsp;</th>
                                <th className="text-right">Price</th>
                                <th className="text-right">Quantity</th>
                                <th className="text-right">Total</th>
                            </tr>
                        </thead>
                        <tbody>
                            {this.state.order.details.map(function(item, index) {
                                return <tr key={index}>
                                    <td>{item.itemId}</td>
                                    <td className="text-right">{KMS.String.toCurrency(item.unitPrice)}</td>
                                    <td className="text-right">{item.quantity}</td>
                                    <td className="text-right">{KMS.String.toCurrency(item.unitPrice * item.quantity)}</td>
                                </tr>;
                            }, this)}
                        </tbody>
                        <tfoot>
                            <tr>
                                <th colSpan="3" className="text-right">Tax ({this.state.order.taxRate * 100}%)</th>
                                <td className="text-right">{KMS.String.toCurrency(this.state.order.subTotal * this.state.order.taxRate)}</td>
                            </tr>
                            <tr>
                                <th colSpan="3" className="text-right">Shipping</th>
                                <td className="text-right">{KMS.String.toCurrency(this.state.order.shippingFee)}</td>
                            </tr>
                            <tr>
                                <th colSpan="3" className="text-right">Total</th>
                                <td className="text-right">{KMS.String.toCurrency(this.state.order.subTotal * (1 + this.state.order.taxRate) + this.state.order.shippingFee)}</td>
                            </tr>
                        </tfoot>
                    </Table>
                    <Button type="primary" cls="pull-right" text="Order" icon="ok" />
                </Column>
            </Row>
        </ContainerFluid>;
    },
    getInitialState: function() {
        return { order: { shippingAddress: {}, billingAddress: {}, details: [] }, headers: ['Item', 'Price', 'Quantity', 'Sub Total'] };
    },
    componentWillMount: function() {
        $.get('/api/orders/preview-order', function(data) {console.log(data);
            this.setState({ order: data });
        }.bind(this));
    }
});
