// webui/react/app/areas/product/product.jsx
'use strict';

import Storage from '../../bootstrap/storage';
import ProductImage from './product-image';
import Utils from '../../bootstrap/utils';
import ProductQuantity from './product-quantity';
import AddToCartButton from './add-to-cart-button';
import PubSub from '../../bootstrap/pubsub';
import Cache from '../../bootstrap/cache';

class Product extends React.Component {
  constructor(props, context) {
    super(props, context);
    this.state = {
      id: context.router.getCurrentParams().id,
      product: { id: '', items: [], reviews: [], avgRating: 0 },
      activeItem: { price: 0, quantity: 10 },
      quantity: 1
    };
  }

  render() {
    const product = this.state.product;

    return <div className="container-fluid">
      <ol className="breadcrumb">
        <li><a href="#home">Home</a></li>
        <li><a href="#products">Products</a></li>
        <li className="active">{product.name}</li>
      </ol>
      <div className="row">
        <div className="col-sm-6">
          <div className="panel panel-default product-item text-center">
            <div className="panel panel-body">
                <ProductImage data={product} />
            </div>
            <div className="panel panel-footer">
                <div className="btn-group" role="group">
                  {product.items.map((item, index) => {
                    const type = item.id === this.state.activeItem.id ? 'primary' : 'default';
                    return <button type="button" className={'btn btn-sm btn-' + type} key={index} onClick={this.setActiveItem.bind(this, item)}>
                        {item.name}
                    </button>;
                  }, this)}
                </div>
              </div>
            </div>
          </div>
          <div className="col-sm-6">
            <div className="row">
              <div className="col-sm-12"><h3>{product.name}</h3></div>
              <div className="col-sm-12"><p>{product.description}</p></div>
              <div className="col-sm-12"><h3>{Utils.toCurrency(this.state.activeItem.price)}</h3></div>
              <div className="col-sm-12">
                <div className="col-sm-3">
                    <ProductQuantity quantityInStock={this.state.activeItem.quantity} quantity={this.state.quantity} onChange={this.setQuantity.bind(this)} />
                </div>
                <div className="col-sm-3">
                  <AddToCartButton quantity={this.state.activeItem.quantity} onClick={this.addToCart.bind(this)} />
                </div>
              </div>
            </div>
        </div>
      </div>
    </div>;
  }

  componentWillMount() {
    Storage.getProduct(this.state.id).done(data => {
      this.setState({ product: data });
      this.setState({ activeItem: data.items[0] });
    });
  }

  setActiveItem(item) {
    this.setState({ activeItem: item });
  }

  setQuantity(event) {
    this.setState({ quantity: event.target.value });
  }

  addToCart() {
    const cartItem = {
      cartId: Cache.get('cartId'),
      itemId: this.state.activeItem.id,
      quantity: this.state.quantity
    };
    Storage.addCartItem(cartItem).done(() => PubSub.publish('updateCart'));
  }
}

Product.contextTypes = { router: React.PropTypes.func.isRequired };

export default Product;

// webui/vue/src/components/products/product.vue
<template>
  <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#/">Home</a></li>
        <li class="breadcrumb-item"><a href="#/products">Products</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
      </ol>
    </nav>
    <section class="row">
      <div class="col-md-6 text-md-center">
        <div class="card">
          <div class="card-body">
              <img :src="'images/products/' + product.id + '.jpg'" v-if="product.id" />
            </a>
          </div>
          <div class="card-footer">
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn"
                      v-bind:class="{'btn-primary': item.id === product.activeItem.id, 'btn-outline-primary': item.id !== product.activeItem.id}" 
                      v-for="item in product.items" :key="item.id">
                {{ item.name }}
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>{{ product.name }}</h3>
        <p>{{ product.description }}</p>
        <h3 v-if="product.activeItem.price">{{ toCurrency(product.activeItem.price) }}</h3>
        <div class="row">
          <div class="col-md-3">
            <input  type="number" class="form-control text-right" 
                    min="1" v-bind:max="product.activeItem.quantity" step="1"
                    v-model="product.quantity" v-if="product.activeItem.quantity > 0" />
            <input type="text" value="0" v-if="product.activeItem.quantity === 0" />
          </div>
          <div class="col-md-3">
            <button type="button" class="btn btn-primary" v-if="product.activeItem.quantity > 0" v-on:click="addToCart">Add to Cart</button>
            <button type="button" class="btn btn-danger" v-if="product.activeItem.quantity === 0">Sold out</button>
          </div>
        </div>
      </div>
    </section>
    <p></p>
    <h2>Reviews</h2>
    <div class="card" v-for="review in product.reviews" :key="review.id">
      <div class="card-body">
        <h3>{{ review.headline }}</h3>
        <p class="text-muted"><strong>{{ review.author }}</strong></p>
        <p>{{ review.content }}</p>
      </div>
    </div>
  </div>
</template>
<script>
import { mapState, mapActions } from 'vuex';
import CommonService from '~/core/common';

export default {
  computed: {
    ...mapState(['product'])
  },
  methods: {
    ...mapActions(['findProductById']),
    toCurrency: CommonService.toCurrency,
    addToCart: function() {
      console.log(this, this.product.activeItem.id, this.product.quantity);
    },
  },
  mounted() {
    this.findProductById(this.$route.params.id);
  },
};
</script>
