// webui/react/app/areas/product/products.jsx
'use strict';

import Storage from '../../bootstrap/storage';
import ProductImage from './product-image';

export default class Products extends React.Component {
  constructor() {
    super();
    this.state = { products: [] };
  }

  render() {
    return <div className="container-fluid">
      <ol className="breadcrumb">
        <li><a href="#home">Home</a></li>
        <li className="active">Products</li>
      </ol>
      <div className="row">
        {this.state.products.map((product, index) => {
          return <div className="col-sm-3" key={index}>
            <div className="panel panel-default product-item text-center">
              <div className="panel panel-body">
                <a href={'#products/' + product.id}>
                  <ProductImage data={product} />
                </a>
              </div>
              <div className="panel panel-footer">
                <h4>
                  <a href={'#products/' + product.id}>{product.name}</a>
                </h4>
              </div>
            </div>
          </div>;
        }, this)}
      </div>
    </div>;
  }

  componentDidMount() {
    Storage.getProducts().done(data => this.setState({ products: data }));
  }
}

// webui/vue/src/components/products/products.vue
<template>
  <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#/">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Products</li>
      </ol>
    </nav>
    <section class="row">
      <article class="col-sm-3 mb-md-4 text-md-center" v-for="prod in products" :key="prod.id">
        <div class="card">
          <div class="card-body">
            <a :href="'#/products/' + prod.id">
              <img :src="'images/products/' + prod.id + '.jpg'" />
            </a>
          </div>
          <div class="card-footer text-muted">
            <a :href="'#/products/' + prod.id">{{ prod.name }}</a>
          </div>
        </div>
      </article>
    </section>
  </div>
</template>
<script>
import { mapState, mapActions } from 'vuex';
export default {
  computed: {
    ...mapState(['products'])
  },
  methods: {
    ...mapActions(['findAllProducts'])
  },
  mounted: function() {
    this.findAllProducts();
  }
};
</script>
