// src/main/webapp/scripts/app/product/product.jsx
var Product = React.createClass({
    render: function() {
        var prod = this.state.product;

        var quantityField = <input type="text" className="form-control" value="0" disabled />;
        var addToCartButton = <button type="button" className="btn btn-sm btn-danger" disabled="disabled">Sold out</button>;
        if (this.state.selectedItem.quantity > 0) {
            quantityField = <input  type="number" id="quantity" className="form-control text-right" 
                                    min="1" max={this.state.selectedItem.quantity} step="1" defaultValue="1" />;
            addToCartButton = <Button type="primary" icon="shopping-cart" text="Add to Cart" onClick={this.addToCart} />;
        }

        return <ContainerFluid>
            <Breadcrumb list={ [{text: 'Home', path: '#home'}, {text: 'Products', path: '#products'}, {text: this.state.product.name}] } />
            <Row>
                <Column colSpan="6">
                    <Panel cls="product-item text-center">
                        <PanelBody>
                            <img src={prod.id ? 'assets/products/' + prod.id + '.jpg' : ''} alt={prod.name} />
                        </PanelBody>
                        <PanelFooter>
                            <div className="btn-group" role="group">
                                {prod.items.map(function(item, index) {
                                    var type = item.id === this.state.selectedItem.id ? 'primary' : 'default';
                                    return <Button key={index} text={item.name} type={type} onClick={this.selectItem.bind(this, item)} />
                                }, this)}
                            </div>
                        </PanelFooter>
                    </Panel>
                </Column>
                <Column colSpan="6">
                    <Row>
                        <Column colSpan="12"><h2>{prod.name}</h2></Column>
                        <Column colSpan="12"><h4>{prod.description}</h4></Column>
                        <Column colSpan="12"><h2>{MSTORE.String.toCurrency(this.state.selectedItem.price)}</h2></Column>
                        <Column colSpan="3">
                            {quantityField}
                        </Column>
                        <Column colSpan="3">
                            {addToCartButton}
                        </Column>
                    </Row>
                </Column>
                <Column colSpan="12">
                    <h2>REVIEWS</h2>
                    <p>
                        <input  type="hidden" 
                                id="ratingScore" 
                                className="rating"
                                data-filled="fa fa-star fa-3x" 
                                data-empty="fa fa-star-o fa-3x" 
                                data-readonly />
                    </p>
                    {prod.reviews.map(function(review, index) {
                        return <Container key={index} cls="well">
                            <h3><strong>{review.headline}</strong></h3>
                            <p className="text-muted"><strong>{review.author}</strong></p>
                            <p>{review.content}</p>
                            <p>Rating: <strong className="text-primary">{review.rating}</strong></p>
                        </Container>;
                    }, this)}
                </Column>
            </Row>
        </ContainerFluid>;
    },
    getInitialState: function() {
        return { product: { id: '', items: [], reviews: [], ratingScore: 0 }, selectedItem: { price: 0, quantity: 10 } };
    },
    componentDidMount: function() {
        var productId = this.props.params[0];
        $.get('/api/products/' + productId, function(data) {
            this.setState({ product: data });
            if (this.state.product.items.length > 0) {
                this.setState({ selectedItem: this.state.product.items[0] });
            }
            $('#ratingScore').rating('rate', this.state.product.ratingScore);
        }.bind(this));
    },
    selectItem: function(item) {
        this.setState({ selectedItem: item });
    },
    addToCart: function() {
        var itemId = this.state.selectedItem.id,
            quantity = $('#quantity').val();
        if (MSTORE.Cache.get('cartId')) {
            this.updateCart(MSTORE.Cache.get('cartId'), itemId, quantity);
        } else {
            $.get('/api/carts/cart-id', function(data) {
                MSTORE.Cache.set('cartId', data);
                this.updateCart(data, itemId, quantity);
            }.bind(this));
        }
    },
    updateCart: function(cartId, itemId, quantity) {
        $.ajax({
            url: '/api/carts/items',
            type: 'post',
            contentType: "application/json; charset=utf-8",
            data: JSON.stringify({ cartId: cartId, itemId: itemId, quantity: quantity })
        }).done(function (data) {
            MSTORE.PubSub.publish('updateCart');
        });
    }
});

// webui/vue/src/components/products/product.vue
<template>
  <div>
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="#/">Home</a></li>
        <li class="breadcrumb-item"><a href="#/products">Products</a></li>
        <li class="breadcrumb-item active" aria-current="page">{{ product.name }}</li>
      </ol>
    </nav>
    <section class="row">
      <div class="col-md-6 text-md-center">
        <div class="card">
          <div class="card-body">
              <img :src="'images/products/' + product.id + '.jpg'" v-if="product.id" />
            </a>
          </div>
          <div class="card-footer">
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="btn"
                      v-bind:class="{'btn-primary': item.id === product.activeItem.id, 'btn-outline-primary': item.id !== product.activeItem.id}" 
                      v-for="item in product.items" :key="item.id">
                {{ item.name }}
              </button>
            </div>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>{{ product.name }}</h3>
        <p>{{ product.description }}</p>
        <h3 v-if="product.activeItem.price">{{ toCurrency(product.activeItem.price) }}</h3>
        <div class="row">
          <div class="col-md-3">
            <input  type="number" class="form-control text-right" 
                    min="1" v-bind:max="product.activeItem.quantity" step="1"
                    v-model="product.quantity" v-if="product.activeItem.quantity > 0" />
            <input type="text" value="0" v-if="product.activeItem.quantity === 0" />
          </div>
          <div class="col-md-3">
            <button type="button" class="btn btn-primary" v-if="product.activeItem.quantity > 0" v-on:click="addToCart">Add to Cart</button>
            <button type="button" class="btn btn-danger" v-if="product.activeItem.quantity === 0">Sold out</button>
          </div>
        </div>
      </div>
    </section>
    <p></p>
    <h2>Reviews</h2>
    <div class="card" v-for="review in product.reviews" :key="review.id">
      <div class="card-body">
        <h3>{{ review.headline }}</h3>
        <p class="text-muted"><strong>{{ review.author }}</strong></p>
        <p>{{ review.content }}</p>
      </div>
    </div>
  </div>
</template>
<script>
import { mapState, mapActions } from 'vuex';
import CommonService from '~/core/common';

export default {
  computed: {
    ...mapState(['product'])
  },
  methods: {
    ...mapActions(['findProductById']),
    toCurrency: CommonService.toCurrency,
    addToCart: function() {
      console.log(this, this.product.activeItem.id, this.product.quantity);
    },
  },
  mounted() {
    this.findProductById(this.$route.params.id);
  },
};
</script>
